#!/usr/bin/env bash
# Builds CodexDesktop for Windows with a bundled Java runtime.
#
#   scripts/package-windows.sh            -> app-image  (dist/CodexDesktop/CodexDesktop.exe)
#   scripts/package-windows.sh installer  -> also an installer (dist/CodexDesktop-<ver>.exe)
#
# The installer target needs the WiX Toolset on PATH; the app-image target does not.
# Idempotent: the output directory is rebuilt from scratch on every run.
set -euo pipefail

TYPE="${1:-app-image}"
APP_NAME="CodexDesktop"
APP_VERSION="0.1.0"
VENDOR="CodexDesktop"
MAIN_CLASS="com.codexdesktop.Launcher"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# Prefer an explicit JAVA_HOME; fall back to whatever java is on PATH.
if [[ -n "${JAVA_HOME:-}" ]]; then
  JPACKAGE="$JAVA_HOME/bin/jpackage"
else
  JPACKAGE="jpackage"
fi

MVN="${MVN:-mvn}"

echo "==> Building jars"
"$MVN" -B clean package

INPUT_DIR="target/app"
OUTPUT_DIR="dist"
MAIN_JAR="codex-desktop.jar"
ICON="packaging/codex-desktop.ico"

if [[ ! -f "$INPUT_DIR/$MAIN_JAR" ]]; then
  echo "!! $INPUT_DIR/$MAIN_JAR is missing; did the package phase run?" >&2
  exit 1
fi

rm -rf "$OUTPUT_DIR" 2>/dev/null || true
if [[ -d "$OUTPUT_DIR/$APP_NAME" ]]; then
  echo "!! $OUTPUT_DIR/$APP_NAME could not be removed - close the running app and retry." >&2
  exit 1
fi
mkdir -p "$OUTPUT_DIR"

echo "==> Running jpackage (type: $TYPE)"
ARGS=(
  --type "$TYPE"
  --name "$APP_NAME"
  --app-version "$APP_VERSION"
  --vendor "$VENDOR"
  --description "JavaFX desktop client for the Codex CLI running in WSL"
  --input "$INPUT_DIR"
  --main-jar "$MAIN_JAR"
  --main-class "$MAIN_CLASS"
  --dest "$OUTPUT_DIR"
  # A trimmed runtime is generated by jpackage; these are the modules the app actually needs.
  --add-modules java.base,java.desktop,java.logging,java.naming,java.management,java.prefs,java.scripting,java.xml,jdk.unsupported,jdk.crypto.ec
  --java-options "-Dfile.encoding=UTF-8"
  --java-options "-Dprism.lcdtext=false"
  --java-options "-Xmx512m"
)

if [[ -f "$ICON" ]]; then
  ARGS+=(--icon "$ICON")
fi

if [[ "$TYPE" != "app-image" ]]; then
  ARGS+=(
    --win-dir-chooser
    --win-menu
    --win-shortcut
    --win-per-user-install
  )
fi

"$JPACKAGE" "${ARGS[@]}"

echo
echo "==> Done"
if [[ "$TYPE" == "app-image" ]]; then
  echo "    $OUTPUT_DIR/$APP_NAME/$APP_NAME.exe"
else
  ls -1 "$OUTPUT_DIR"
fi
